using FeatherQR;
using ZXingCpp;

namespace QRInteropFixtures;

/// <summary>
/// Encoder interoperability spot check: symbols generated by FeatherQR's
/// Micro QR encoder are rendered to luminance images in memory and decoded with
/// zxing-cpp (via the ZXingCpp .NET wrapper), an independent implementation
/// lineage. This is the external verification required by the encoder MVT until
/// the interop CI pipeline exists.
/// </summary>
public static class MicroQRSpotCheck
{
    private const int QuietZoneModules = 2; // Micro QR specification quiet zone
    private const int PixelsPerModule = 8;

    private static readonly (string Text, MicroQREccLevel Ecc, MicroQRSegmentation Segmentation)[] cases =
    [
        ("12345", MicroQREccLevel.ErrorDetectionOnly, MicroQRSegmentation.Single),  // M1
        ("0123456789", MicroQREccLevel.L, MicroQRSegmentation.Single),              // M2-L boundary
        ("12345678", MicroQREccLevel.M, MicroQRSegmentation.Single),                // M2-M boundary
        ("HELLO WORLD 14", MicroQREccLevel.L, MicroQRSegmentation.Single),          // M3-L alphanumeric boundary
        ("byte hi", MicroQREccLevel.M, MicroQRSegmentation.Single),                 // M3-M byte
        ("HELLO WORLD PLUS 21ST", MicroQREccLevel.L, MicroQRSegmentation.Single),   // M4-L alphanumeric boundary
        ("bytes m4 mode", MicroQREccLevel.M, MicroQRSegmentation.Single),           // M4-M byte boundary
        ("bytes!!!!", MicroQREccLevel.Q, MicroQRSegmentation.Single),               // M4-Q byte boundary
        ("こんにちは", MicroQREccLevel.L, MicroQRSegmentation.Single),               // Kanji, M3-L (5 of 6 characters)
        ("脂至肢漢", MicroQREccLevel.M, MicroQRSegmentation.Single),                  // Kanji, M3-M boundary (4 characters, 3-bit count)
        ("こんにちは世界です", MicroQREccLevel.L, MicroQRSegmentation.Single),        // Kanji, M4-L boundary (9 characters, 4-bit count)
        ("日本語符号化試験", MicroQREccLevel.M, MicroQRSegmentation.Single),          // Kanji, M4-M boundary (8 characters)
        ("漢字試験用", MicroQREccLevel.Q, MicroQRSegmentation.Single),                // Kanji, M4-Q boundary (5 characters)
        ("こんにち～", MicroQREccLevel.L, MicroQRSegmentation.Single),               // ～ has no Kanji cell: UTF-8 (15 bytes, M4-L, no ECI)
        ("日本語12345", MicroQREccLevel.L, MicroQRSegmentation.Optimal),           // Kanji plan: Kanji + Numeric at M3-L (UTF-8 needs M4)
        ("東京12", MicroQREccLevel.M, MicroQRSegmentation.Optimal),                // Kanji plan at M3-M (UTF-8 needs M4)
        ("日本語123456789", MicroQREccLevel.L, MicroQRSegmentation.Optimal),       // Kanji plan at M3-L; no Micro QR symbol holds it as UTF-8
        ("東京タワー333m", MicroQREccLevel.L, MicroQRSegmentation.Optimal),        // Kanji plan with a Byte run of ASCII, M4-L (19 UTF-8 bytes fit nowhere)
    ];

    public static int Run()
    {
        var reader = new BarcodeReader
        {
            Formats = BarcodeFormat.MicroQRCode,
            TryHarder = true,
        };

        var failures = 0;
        foreach (var (text, ecc, segmentation) in cases)
        {
            var options = new MicroQRCodeGeneratorOptions { QuietZoneSize = QuietZoneModules, Segmentation = segmentation };
            var calculated = Sizing.Required(text.AsSpan(), ecc, options);
            var modules = new byte[calculated.BufferSize];
            MicroQRCodeGenerator.Create(text.AsSpan(), ecc, modules, options);

            var luminance = RenderLuminance(modules, calculated.Size, PixelsPerModule);
            var widthPixels = calculated.Size * PixelsPerModule;
            var image = new ImageView(luminance, widthPixels, widthPixels, ImageFormat.Lum);

            var results = reader.From(image);
            if (results.Length == 1 && results[0].Text == text)
            {
                Console.WriteLine($"PASS: {calculated.Version}/{ecc} \"{text}\" decoded as {results[0].Format}");
            }
            else
            {
                failures++;
                var detail = results.Length == 0 ? "not detected" : $"decoded {results.Length} symbol(s), first text \"{results[0].Text}\"";
                Console.Error.WriteLine($"FAIL: {calculated.Version}/{ecc} \"{text}\" -> {detail}");
            }
        }

        Console.WriteLine(failures == 0
            ? $"spot-check-microqr: all {cases.Length} symbols decoded by zxing-cpp"
            : $"spot-check-microqr: {failures}/{cases.Length} FAILED");
        return failures == 0 ? 0 : 1;
    }

    /// <summary>Renders a byte-per-module matrix to an 8-bit luminance image (0 = dark, 255 = light).</summary>
    private static byte[] RenderLuminance(byte[] modules, int matrixSize, int pixelsPerModule)
    {
        var widthPixels = matrixSize * pixelsPerModule;
        var luminance = new byte[widthPixels * widthPixels];

        for (var row = 0; row < matrixSize; row++)
        {
            for (var col = 0; col < matrixSize; col++)
            {
                var value = modules[row * matrixSize + col] != 0 ? (byte)0 : (byte)255;
                var pixelRow = row * pixelsPerModule;
                var pixelCol = col * pixelsPerModule;
                for (var y = 0; y < pixelsPerModule; y++)
                {
                    var offset = (pixelRow + y) * widthPixels + pixelCol;
                    luminance.AsSpan(offset, pixelsPerModule).Fill(value);
                }
            }
        }

        return luminance;
    }
}
