name: Lint Dotnet

on:
  workflow_dispatch:
  schedule:
    - cron: 0 1 * * 1 # At AM10:00 JST on Monday

jobs:
  lint:
    permissions:
      contents: write
      pull-requests: write
    uses: guitarrapc/actions/.github/workflows/reusable-dotnet-lint.yaml@74f3c78b2bcb7545e4c4911c5cf34124faecd2d2 # v1.3.2
    with:
      sln-file: "FeatherQR.slnx"
