name: Lint Dotnet

on:
  workflow_dispatch:
  schedule:
    - cron: 0 1 * * 1 # At AM10:00 JST on Monday

jobs:
  lint:
    permissions:
      contents: write
      pull-requests: write
    uses: guitarrapc/actions/.github/workflows/reusable-dotnet-lint.yaml@b9e79bebea40ce159375351b13af8b3c0b530937 # v1.3.1
    with:
      sln-file: "FeatherQR.slnx"
