name: PR Harness

on:
  pull_request:
    branches: [main]

jobs:
  harness:
    permissions:
      contents: read
      pull-requests: read
    uses: guitarrapc/actions/.github/workflows/pr-harness.yaml@main
    with:
      license-check: true
      allow-licenses: "Apache-2.0,BSD-2-Clause,BSD-3-Clause,ISC,MIT,MPL-2.0,Zlib,Unicode-3.0,LicenseRef-scancode-google-patent-license-golang"
      exclude-license-input-paths: "tools/"
